### PR TITLE
fix: easy supports list/array/sequence type as parameter

### LINKED ISSUE #347: `cadCAD.tools.easy_run` is unable to handle Config Parameters on which the values are `Sequence` like.

### PR DESCRIPTION
**Pull request by zcstarr**
This change avoids using df.assign for adding parameters to the config dataframe, this allows for lists to be used as parameters.

Fixes #347

### CODE REVIEW

**Comment by danlessa** [comment]
SGTM

**Comment by zcstarr** [comment]
@emanuellima1 just a quick ping here, I think you're the only reviewer with write access

**Comment by zcstarr** [comment]
> LGTM

thanks for the review!

**Review by emanuellima1 — APPROVED** [review]
LGTM

**Pull request merged**
