### PR TITLE
Progress bars for multi_proc + detailed printing + better multi_proc performance + performance tweaks

### PR DESCRIPTION
**Pull request by danlessa**
progress bars for multi_proc
1. tqdm progress bars for the multi_proc mode for configuration loading, PSUB execution, and result flattening

sim dimensions printing on exec init
2. More informative printing when executing cadCAD - it shows the dimensions of the first sim

changed n_nodes on ppool to none
3. Changed the PPool on the multi_proc exec_method to have n_node = None. This makes the number of nodes equal to the number of CPUs. This avoids crashes when doing huge parameter sweeps with few cpus, like 1000 sweeps/cpu

refactor for performance improvement
4. Did a pontual refactor on configuration/_init.py. This generates some performance improvements when dealing with a lot of sweeps

### CODE REVIEW

**Comment by danlessa** [comment]
I've noticed that trying to run the merge_branch on a sim with just one param sweep throws an error due to the multi_proc being changed to single_proc

configuration:
https://github.com/BlockScience/filecoin/blob/test_plan/src/sim/config_price.py

executor definition
https://github.com/BlockScience/filecoin/blob/test_plan/src/sim/run.py

**Comment by JEJodesty** [comment]
In General:
isolate into separate PRs
propagate that tuple line

**Comment by JEJodesty** [comment]
Priority:
PR to `merge_staging`

changed n_nodes on ppool to none
3. Changed the PPool on the multi_proc exec_method to have n_node = None. This makes the number of nodes equal to the number of CPUs. This avoids crashes when doing huge parameter sweeps with few cpus, like 1000 sweeps/cpu

**Comment by JEJodesty** [comment]
@danlessa 
Broken into new PRs
#111 tqdm progress bars for multi_proc mode
#110 Dimentionality printing when starting an simulation
#109 Refactor on apply_identity_funcs for performance improvement
#108 Change number of nodes on multiproc to 'None'

**Comment by JEJodesty** [comment]
@danlessa 
Broken into new PRs
#111 tqdm progress bars for multi_proc mode
#110 Dimentionality printing when starting an simulation
#109 Refactor on apply_identity_funcs for performance improvement
#108 Change number of nodes on multiproc to 'None'

**Pull request closed without merging**
