### PR TITLE
Fixed broken links in documentation readme

### PR DESCRIPTION
**Pull request by rogervs**
Fixed two  broken links that point to Robot and Marbles examples in cadCAD-org/demos repo

### CODE REVIEW

**Review by markusbkoch — APPROVED** [review]
lgtm, thanks!

**Comment by BenSchZA** [comment]
The merge branch/repo seems to have been deleted @rogervs

**Comment by rogervs** [comment]
@BenSchZA I deleted it after it was approved to clear up my github. Did I delete it to early? Or should I have not deleted it?

**Comment by BenSchZA** [comment]
@rogervs It seems these changes were merged, but the PR wasn't closed - I think branches are being merged manually and locally, rather than through PRs.

**Pull request closed without merging**
