### PR TITLE
Update CHANGELOG: Nix addition

### PR DESCRIPTION
**Pull request by BenSchZA**
See issue #131 and commit hash b86e59907cdd6c1512bcd780d81abe676010f0ee

### CODE REVIEW

**Comment by BenSchZA** [comment]
@JEJodesty I don't think I have permission to add assignee (myself) or reviewer.

**Comment by JEJodesty** [comment]
@BenSchZA 
Access given.
Let me know if there's a problem with the next PR.
Thank you for your contribution! :)

**Comment by JEJodesty** [comment]
@BenSchZA 
Access given.
Let me know if there's a problem with the next PR.
Thank you for your contribution! :)

**Comment by JEJodesty** [comment]
> See issue #131 and commit hash [b86e599](https://github.com/cadCAD-org/cadCAD/commit/b86e59907cdd6c1512bcd780d81abe676010f0ee)

peeped that as well but we should leave it there as well in my opinion

**Comment by JEJodesty** [comment]
@BenSchZA 
Access given, **but** never submit a PR directly to master.
Let me know if there's a problem with the next PR.
Thank you for your contribution! :)

**Comment by BenSchZA** [comment]
> @BenSchZA
> Access given,
> **but** never submit a PR directly to master, i will fast-track documentation into master to prevent loss of work in the next release
> 
> Let me know if there's a problem with the next PR.
> Thank you for your contribution! :)

Thanks Josh! It's going to happen again, trust me :sweat_smile: Unfortunate that the default view branch and PR branch are the same: https://github.com/isaacs/github/issues/1401

**Pull request merged**
